import { StrictMode, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles/global.css'
import './styles/app.css'
import { customerRepository, orderRepository } from './data/repositories'

const Icon = ({ name, size = 18 }) => {
  const paths = { grid: <><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>, users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>, box: <><path d="m21 8-9-5-9 5 9 5 9-5Z"/><path d="M3 8v9l9 5 9-5V8M12 13v9"/></>, chart: <><path d="M3 3v18h18"/><path d="m7 16 4-5 3 3 5-7"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, chevron: <path d="m6 9 6 6 6-6"/>, plus: <><path d="M12 5v14M5 12h14"/></>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>, close: <><path d="M6 6l12 12M18 6 6 18"/></>, clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, check: <path d="m5 12 4 4L19 6"/> }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

const navItems = [{ label: 'ภาพรวม', icon: 'grid' }, { label: 'ลูกค้า', icon: 'users' }, { label: 'คำสั่งซื้อ', icon: 'box' }]
const statusOptions = [{ key: 'planning', label: 'รอเริ่มงาน', tone: 'gray' }, { key: 'production', label: 'กำลังเตรียมสินค้า', tone: 'blue' }, { key: 'ready', label: 'พร้อมจัดส่ง', tone: 'green' }, { key: 'shipped', label: 'จัดส่งแล้ว', tone: 'purple' }]

function App() {
  const [activeNav, setActiveNav] = useState('ภาพรวม')
  const [customers, setCustomers] = useState(customerRepository.list())
  const [orders, setOrders] = useState(orderRepository.list())
  const [query, setQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState('ทั้งหมด')
  const [modal, setModal] = useState(null)
  const [toast, setToast] = useState('')

  const showToast = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const visibleCustomers = useMemo(() => customers.filter((customer) => `${customer.name} ${customer.company} ${customer.phone}`.toLowerCase().includes(query.toLowerCase())), [customers, query])
  const visibleOrders = useMemo(() => orders.filter((order) => (statusFilter === 'ทั้งหมด' || order.status === statusFilter) && `${order.customer} ${order.number} ${order.product}`.toLowerCase().includes(query.toLowerCase())), [orders, query, statusFilter])

  const changeOrderStatus = (id, status) => { const next = statusOptions.find((item) => item.key === status); setOrders((items) => items.map((item) => item.id === id ? { ...item, status, statusLabel: next.label } : item)); showToast(`อัปเดตสถานะเป็น “${next.label}” แล้ว`) }
  const addCustomer = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = form.get('name'); const newCustomer = { id: `cus_${Date.now()}`, name, initials: name.slice(0, 2), email: form.get('email'), phone: form.get('phone'), company: form.get('company'), status: 'ลูกค้าใหม่', statusTone: 'info', lastOrder: 'ยังไม่มีคำสั่งซื้อ', total: '฿ 0', avatarTone: 'avatar-sky', notes: form.get('notes') || 'ยังไม่มีโน้ต', activities: [{ date: 'วันนี้', title: 'สร้างโปรไฟล์ลูกค้า', detail: 'เพิ่มโดย นรินทร์ ส.' }] }; setCustomers((items) => [newCustomer, ...items]); setModal(null); showToast('เพิ่มลูกค้าใหม่แล้ว') }
  const addOrder = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const customer = customers.find((item) => item.id === form.get('customerId')); const order = { id: `ord_${Date.now()}`, number: `BF-${String(Date.now()).slice(-6)}`, customerId: customer.id, customer: customer.company, product: form.get('product'), quantity: form.get('quantity'), total: form.get('total'), delivery: form.get('delivery'), status: 'planning', statusLabel: 'รอเริ่มงาน' }; setOrders((items) => [order, ...items]); setModal(null); showToast('สร้างคำสั่งซื้อใหม่แล้ว') }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">b</div><span>biofresh</span></div><div className="workspace-switcher"><div className="workspace-icon">S</div><div><small>Workspace</small><strong>ฝ่ายขาย</strong></div><Icon name="chevron" size={15}/></div><nav className="main-nav" aria-label="เมนูหลัก"><p className="nav-label">เมนูหลัก</p>{navItems.map((item) => <button key={item.label} className={`nav-item ${activeNav === item.label ? 'active' : ''}`} onClick={() => { setActiveNav(item.label); setQuery(''); setStatusFilter('ทั้งหมด') }}><Icon name={item.icon}/><span>{item.label}</span>{item.label === 'ลูกค้า' && <em>{customers.length}</em>}{item.label === 'คำสั่งซื้อ' && <em>{orders.length}</em>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Icon name="clock"/><span>กิจกรรมล่าสุด</span></button><div className="profile"><div className="avatar avatar-sky">NS</div><div><strong>นรินทร์ ส.</strong><small>Sales manager</small></div><Icon name="more" size={16}/></div></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{activeNav}</strong></div><div className="top-actions"><button className="icon-button"><Icon name="search"/></button><button className="icon-button notification"><Icon name="bell"/><i/></button><div className="avatar avatar-indigo">NS</div></div></header>
      <div className="page-content"><section className="page-heading"><div><p className="eyebrow">SALES WORKSPACE · MOCK MODE</p><h1>{activeNav === 'ภาพรวม' ? <>สวัสดี, นรินทร์ <span>✦</span></> : activeNav}</h1><p className="subheading">{activeNav === 'ภาพรวม' ? 'พื้นที่ทำงานสำหรับติดตามลูกค้าและคำสั่งซื้อของทีม' : activeNav === 'ลูกค้า' ? 'ฐานข้อมูลประวัติลูกค้าและกิจกรรมล่าสุด' : 'ติดตามสถานะคำสั่งซื้อของทีมแบบ end-to-end'}</p></div><button className="primary-button" onClick={() => setModal(activeNav === 'ลูกค้า' ? 'customer-form' : 'order-form')}><Icon name="plus" size={17}/> {activeNav === 'ลูกค้า' ? 'เพิ่มลูกค้า' : 'เพิ่มคำสั่งซื้อ'}</button></section>
        {activeNav === 'ภาพรวม' && <Overview orders={orders} customers={customers} onNavigate={setActiveNav} onOpenOrder={(order) => setModal({ type: 'order', order })} />}
        {activeNav === 'ลูกค้า' && <CustomerDirectory customers={visibleCustomers} query={query} setQuery={setQuery} onOpen={(customer) => setModal({ type: 'customer', customer })} />}
        {activeNav === 'คำสั่งซื้อ' && <OrderTracker orders={visibleOrders} query={query} setQuery={setQuery} statusFilter={statusFilter} setStatusFilter={setStatusFilter} onOpen={(order) => setModal({ type: 'order', order })} onStatus={changeOrderStatus} />}
      </div></main>
    {modal === 'customer-form' && <Modal title="เพิ่มลูกค้าใหม่" onClose={() => setModal(null)}><CustomerForm onSubmit={addCustomer} /></Modal>}
    {modal === 'order-form' && <Modal title="สร้างคำสั่งซื้อ" onClose={() => setModal(null)}><OrderForm customers={customers} onSubmit={addOrder} /></Modal>}
    {modal?.type === 'customer' && <Modal title={modal.customer.name} subtitle={modal.customer.company} onClose={() => setModal(null)}><CustomerDetail customer={modal.customer} orders={orders.filter((order) => order.customerId === modal.customer.id)} onAddOrder={() => setModal('order-form')} /></Modal>}
    {modal?.type === 'order' && <Modal title={modal.order.number} subtitle={modal.order.customer} onClose={() => setModal(null)}><OrderDetail order={modal.order} onStatus={(status) => { changeOrderStatus(modal.order.id, status); setModal({ type: 'order', order: { ...modal.order, status, statusLabel: statusOptions.find((item) => item.key === status).label } }) }} /></Modal>}
    {toast && <div className="toast"><Icon name="check" size={16}/>{toast}</div>}
  </div>
}

function Overview({ orders, customers, onNavigate, onOpenOrder }) { return <><section className="metric-grid"><Metric label="ยอดขายรวม" value="฿ 2,845,200" change="+18.4%" note="จากเดือนที่แล้ว" icon="chart" tone="green"/><Metric label="คำสั่งซื้อทั้งหมด" value={orders.length} change="+12.8%" note="รายการใน mock data" icon="box" tone="blue"/><Metric label="ลูกค้าทั้งหมด" value={customers.length} change="+8.2%" note="โปรไฟล์ในระบบ" icon="users" tone="purple"/><Metric label="ต้องติดตาม" value={orders.filter((order) => order.status === 'planning').length} change="วันนี้" note="คำสั่งซื้อ" icon="clock" tone="orange" alert/></section><section className="dashboard-grid"><div className="card sales-card"><div className="card-heading"><div><h2>ยอดขาย</h2><p>แนวโน้มยอดขายในช่วง 30 วันที่ผ่านมา</p></div><span className="data-badge">Mock data</span></div><div className="chart-wrap"><div className="chart-y"><span>฿ 600k</span><span>฿ 400k</span><span>฿ 200k</span><span>฿ 0</span></div><div className="chart"><div className="grid-lines"><i/><i/><i/><i/></div><svg viewBox="0 0 700 210" preserveAspectRatio="none" className="line-chart"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#5e9cfc" stopOpacity=".22"/><stop offset="100%" stopColor="#5e9cfc" stopOpacity="0"/></linearGradient></defs><path d="M0,168 C45,164 62,143 95,151 S145,173 185,126 S235,139 270,112 S320,85 355,108 S400,118 435,77 S470,65 505,85 S545,115 580,56 S628,74 700,25 L700,210 L0,210 Z" fill="url(#fill)"/><path d="M0,168 C45,164 62,143 95,151 S145,139 185,126 S235,139 270,112 S320,85 355,108 S400,118 435,77 S470,65 505,85 S545,115 580,56 S628,74 700,25" fill="none" stroke="#4d8df7" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><div className="chart-x"><span>1 พ.ค.</span><span>8 พ.ค.</span><span>15 พ.ค.</span><span>22 พ.ค.</span><span>วันนี้</span></div></div></div></div><div className="card recent-card"><div className="card-heading"><div><h2>งานล่าสุด</h2><p>คำสั่งซื้อที่ต้องดูแล</p></div><button className="text-link" onClick={() => onNavigate('คำสั่งซื้อ')}>ดูทั้งหมด <Icon name="arrow" size={14}/></button></div><div className="recent-list">{orders.slice(0, 3).map((order) => <button className="recent-item" key={order.id} onClick={() => onOpenOrder(order)}><div className={`status-dot ${order.status}`}/><div><strong>{order.customer}</strong><small>{order.product}</small></div><span>{order.statusLabel}</span></button>)}</div></div></section><section className="card quick-start"><div><h2>เริ่มต้นใช้งาน</h2><p>ทดลอง workflow หลักของ Sales Workspace ได้จากปุ่มด้านล่าง</p></div><div className="quick-actions"><button onClick={() => onNavigate('ลูกค้า')}><Icon name="users"/> ดูฐานลูกค้า</button><button onClick={() => onNavigate('คำสั่งซื้อ')}><Icon name="box"/> ติดตามคำสั่งซื้อ</button></div></section></> }
function Metric({ label, value, change, note, icon, tone, alert }) { return <div className="metric-card"><div className={`metric-icon ${tone}`}><Icon name={icon} size={19}/></div><p>{label}</p><strong>{value}</strong><div className={`metric-change ${alert ? 'alert' : ''}`}><span>{change}</span><small>{note}</small></div></div> }
function CustomerDirectory({ customers, query, setQuery, onOpen }) { return <section className="card directory-card"><div className="toolbar-row"><div><h2>Customer Directory</h2><p>ค้นหาและเปิดดูประวัติลูกค้าแต่ละราย</p></div><div className="search-input wide"><Icon name="search" size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาชื่อ บริษัท หรือเบอร์โทร..." /></div></div><div className="table-wrap"><table><thead><tr><th>ลูกค้า</th><th>บริษัท</th><th>สถานะ</th><th>คำสั่งซื้อล่าสุด</th><th>ยอดรวม</th><th></th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id} onClick={() => onOpen(customer)} className="clickable-row"><td><div className="customer-cell"><div className={`avatar ${customer.avatarTone}`}>{customer.initials}</div><div><strong>{customer.name}</strong><small>{customer.email}</small></div></div></td><td>{customer.company}</td><td><span className={`status ${customer.statusTone}`}><i/>{customer.status}</span></td><td>{customer.lastOrder}</td><td className="amount">{customer.total}</td><td><Icon name="arrow" size={15}/></td></tr>)}</tbody></table>{!customers.length && <EmptyState text="ไม่พบลูกค้าที่ค้นหา"/>}</div></section> }
function OrderTracker({ orders, query, setQuery, statusFilter, setStatusFilter, onOpen, onStatus }) { return <><section className="card tracker-toolbar"><div className="search-input wide"><Icon name="search" size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาลูกค้า เลขที่ออเดอร์ หรือสินค้า..." /></div><div className="filter-tabs">{[{ key: 'ทั้งหมด', label: 'ทั้งหมด' }, ...statusOptions].map((item) => <button className={statusFilter === item.key ? 'selected' : ''} key={item.key} onClick={() => setStatusFilter(item.key)}>{item.label}</button>)}</div></section><section className="order-board">{statusOptions.map((status) => <div className="order-lane" key={status.key}><div className="lane-heading"><div><span className={`lane-dot ${status.tone}`}/><strong>{status.label}</strong></div><em>{orders.filter((order) => order.status === status.key).length}</em></div>{orders.filter((order) => order.status === status.key).map((order) => <OrderCard key={order.id} order={order} onOpen={onOpen} onStatus={onStatus}/>)}</div>)}</section></> }
function OrderCard({ order, onOpen, onStatus }) { return <article className="order-card" onClick={() => onOpen(order)}><div className="order-top"><div><strong>{order.customer}</strong><small>{order.number}</small></div><span className={`status ${order.status === 'ready' ? 'success' : order.status === 'shipped' ? 'purple' : order.status === 'production' ? 'info' : 'neutral'}`}>{order.statusLabel}</span></div><div className="order-product"><span>สินค้า</span><strong>{order.product}</strong><span>{order.quantity} · {order.total}</span></div><div className="order-footer"><span>ส่ง {order.delivery}</span><button onClick={(event) => { event.stopPropagation(); const index = statusOptions.findIndex((item) => item.key === order.status); onStatus(order.id, statusOptions[Math.min(index + 1, statusOptions.length - 1)].key) }}>เลื่อนสถานะ <Icon name="arrow" size={13}/></button></div></article> }
function CustomerDetail({ customer, orders, onAddOrder }) { return <div className="detail-layout"><div><div className="detail-profile"><div className={`avatar large ${customer.avatarTone}`}>{customer.initials}</div><div><h3>{customer.name}</h3><p>{customer.email} · {customer.phone}</p><span className={`status ${customer.statusTone}`}>{customer.status}</span></div></div><div className="detail-section"><div className="section-heading"><h3>ประวัติกิจกรรม</h3><button className="outline-button" onClick={() => window.alert('ตัวอย่าง: ฟังก์ชันเพิ่มกิจกรรมจะเชื่อมกับ service ภายหลัง')}>+ เพิ่มกิจกรรม</button></div><div className="activity-list">{customer.activities.map((activity) => <div className="activity-item" key={activity.date + activity.title}><div className="activity-icon"><Icon name="check" size={14}/></div><div><strong>{activity.title}</strong><small>{activity.detail}</small><em>{activity.date}</em></div></div>)}</div></div></div><aside className="detail-side"><div className="side-stat"><span>บริษัท</span><strong>{customer.company}</strong></div><div className="side-stat"><span>ยอดซื้อสะสม</span><strong>{customer.total}</strong></div><div className="side-stat"><span>โน้ตฝ่ายขาย</span><p>{customer.notes}</p></div><div className="side-stat"><div className="section-heading"><span>คำสั่งซื้อ</span><button className="mini-add" onClick={onAddOrder}><Icon name="plus" size={14}/></button></div>{orders.length ? orders.map((order) => <button className="mini-order" key={order.id}><strong>{order.number}</strong><small>{order.product}</small><span>{order.statusLabel}</span></button>) : <p className="muted">ยังไม่มีคำสั่งซื้อ</p>}</div></aside></div> }
function OrderDetail({ order, onStatus }) { return <div className="order-detail"><div className="order-detail-summary"><div><span className="eyebrow">ORDER</span><h3>{order.product}</h3><p>{order.customer} · {order.quantity}</p></div><strong>{order.total}</strong></div><div className="detail-info-grid"><div><span>วันที่จัดส่ง</span><strong>{order.delivery}</strong></div><div><span>เลขที่ออเดอร์</span><strong>{order.number}</strong></div><div><span>สถานะปัจจุบัน</span><strong>{order.statusLabel}</strong></div></div><div className="detail-section"><div className="section-heading"><h3>อัปเดตสถานะ</h3><span className="muted">กดเพื่อทดลองเปลี่ยน workflow</span></div><div className="status-stepper">{statusOptions.map((item, index) => <button className={order.status === item.key ? `current ${item.tone}` : ''} key={item.key} onClick={() => onStatus(item.key)}><span>{index + 1}</span>{item.label}</button>)}</div></div><div className="note-box"><Icon name="clock" size={16}/><span>ข้อมูลนี้เป็น mock data และยังไม่ได้บันทึกลงฐานข้อมูลจริง</span></div></div> }
function CustomerForm({ onSubmit }) { return <form className="form-grid" onSubmit={onSubmit}><label>ชื่อลูกค้า<input name="name" required placeholder="เช่น กมลชนก วัฒนากร"/></label><label>บริษัท<input name="company" required placeholder="ชื่อบริษัท"/></label><label>อีเมล<input name="email" type="email" required placeholder="email@company.com"/></label><label>เบอร์โทร<input name="phone" required placeholder="08x-xxx-xxxx"/></label><label className="full-width">โน้ตฝ่ายขาย<textarea name="notes" placeholder="ข้อมูลสำคัญของลูกค้ารายนี้"/></label><div className="form-actions"><button type="submit" className="primary-button">บันทึกลูกค้า</button></div></form> }
function OrderForm({ customers, onSubmit }) { return <form className="form-grid" onSubmit={onSubmit}><label className="full-width">ลูกค้า<select name="customerId" required defaultValue=""> <option value="" disabled>เลือกลูกค้า</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.company}</option>)}</select></label><label className="full-width">สินค้า<input name="product" required placeholder="เช่น Organic Beef Tenderloin"/></label><label>ปริมาณ<input name="quantity" required placeholder="24 กก."/></label><label>ยอดรวม<input name="total" required placeholder="฿ 42,800"/></label><label className="full-width">วันที่จัดส่ง<input name="delivery" required placeholder="เช่น 18 พ.ค. 2025"/></label><div className="form-actions"><button type="submit" className="primary-button">สร้างคำสั่งซื้อ</button></div></form> }
function Modal({ title, subtitle, onClose, children }) { return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="modal-card"><div className="modal-header"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="close-button" onClick={onClose}><Icon name="close" size={17}/></button></div><div className="modal-body">{children}</div></div></div> }
function EmptyState({ text }) { return <div className="empty-state">{text}</div> }

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
